[[case]]
name = "default"
chain = "eq=brightness=0.03:saturation=1.045"

[[case]]
name = "min"
at = "min"
chain = "eq=brightness=0.03:saturation=1.000"

[[case]]
name = "max"
at = "max"
chain = "eq=brightness=0.03:saturation=1.300"
