[[case]]
name = "default"
chain = "hue=s=0,split[holoa0][holob0];[holob0]edgedetect=low=0.1:high=0.3,format=rgb24,lutrgb=r=val*0.5:g=val*0.91:b=val[holoe0];[holoa0]curves=r='0/0.009 0.6/0.14 1/0.78':g='0/0.08 0.6/0.57 1/1':b='0/0.14 0.6/0.83 1/1'[holor0];[holor0][holoe0]blend=all_mode=addition:all_opacity=0.40,hue=h=0,rgbashift=rh=-3:bh=3,drawgrid=x=-1:w=iw+2:h=4:t=1:c=black@0.30,noise=alls=6:allf=t,vignette=angle=0.55"

[[case]]
name = "minimum"
at = "min"
chain = "hue=s=0,split[holoa0][holob0];[holob0]edgedetect=low=0.1:high=0.3,format=rgb24,lutrgb=r=val*0.5:g=val*0.91:b=val[holoe0];[holoa0]curves=r='0/0.009 0.6/0.14 1/0.78':g='0/0.08 0.6/0.57 1/1':b='0/0.14 0.6/0.83 1/1'[holor0];[holor0][holoe0]blend=all_mode=addition:all_opacity=0.00,hue=h=-180,rgbashift=rh=0:bh=0,drawgrid=x=-1:w=iw+2:h=4:t=1:c=black@0.00,noise=alls=0:allf=t,vignette=angle=0.55"

[[case]]
name = "maximum"
at = "max"
chain = "hue=s=0,split[holoa0][holob0];[holob0]edgedetect=low=0.1:high=0.3,format=rgb24,lutrgb=r=val*0.5:g=val*0.91:b=val[holoe0];[holoa0]curves=r='0/0.009 0.6/0.14 1/0.78':g='0/0.08 0.6/0.57 1/1':b='0/0.14 0.6/0.83 1/1'[holor0];[holor0][holoe0]blend=all_mode=addition:all_opacity=1.00,hue=h=180,rgbashift=rh=-8:bh=8,drawgrid=x=-1:w=iw+2:h=4:t=1:c=black@0.55,noise=alls=40:allf=t,vignette=angle=0.55"
