[[case]]
name = "default"
chain = "gblur=sigma=10.0,eq=saturation=1.2"

[[case]]
name = "min"
at = "min"
chain = "gblur=sigma=0.0,eq=saturation=1.2"

[[case]]
name = "max"
at = "max"
chain = "gblur=sigma=20.0,eq=saturation=1.2"
