[[case]]
name = "default"
chain = "split[spka0][spkb0];[spkb0]gblur=sigma=8[spkg0];[spka0][spkg0]blend=all_mode=screen:all_opacity=0.480"

[[case]]
name = "min"
at = "min"
chain = "split[spka0][spkb0];[spkb0]gblur=sigma=8[spkg0];[spka0][spkg0]blend=all_mode=screen:all_opacity=0.000"

[[case]]
name = "max"
at = "max"
chain = "split[spka0][spkb0];[spkb0]gblur=sigma=8[spkg0];[spka0][spkg0]blend=all_mode=screen:all_opacity=0.800"
