[[case]]
name = "default"
chain = "colorbalance=gh=0.320:bh=0.320"

[[case]]
name = "min"
at = "min"
chain = "colorbalance=gh=0.000:bh=0.000"

[[case]]
name = "max"
at = "max"
chain = "colorbalance=gh=0.400:bh=0.400"
