[[case]]
name = "default"
chain = "eq=saturation=0.850:contrast=1.15"

[[case]]
name = "min"
at = "min"
chain = "eq=saturation=1.000:contrast=1.15"

[[case]]
name = "max"
at = "max"
chain = "eq=saturation=0.700:contrast=1.15"
