[[case]]
name = "default"
chain = "noise=alls=15:allf=t,eq=brightness=0.015"

[[case]]
name = "min"
at = "min"
chain = "noise=alls=0:allf=t,eq=brightness=0.000"

[[case]]
name = "max"
at = "max"
chain = "noise=alls=30:allf=t,eq=brightness=0.030"
