[[case]]
name = "default"
chain = "format=rgba,geq=r='r(mod(X+T*9.00+W*1000,W),Y)':g='g(mod(X+T*9.00+W*1000,W),Y)':b='b(mod(X+T*9.00+W*1000,W),Y)':a='alpha(mod(X+T*9.00+W*1000,W),Y)'"

[[case]]
name = "min"
at = "min"
chain = "format=rgba,geq=r='r(mod(X+T*0.30+W*1000,W),Y)':g='g(mod(X+T*0.30+W*1000,W),Y)':b='b(mod(X+T*0.30+W*1000,W),Y)':a='alpha(mod(X+T*0.30+W*1000,W),Y)'"

[[case]]
name = "max"
at = "max"
chain = "format=rgba,geq=r='r(mod(X+T*-30.00+W*1000,W),Y)':g='g(mod(X+T*-30.00+W*1000,W),Y)':b='b(mod(X+T*-30.00+W*1000,W),Y)':a='alpha(mod(X+T*-30.00+W*1000,W),Y)'"
