[[case]]
name = "default"
chain = "split[hla0][hlb0];[hlb0]gblur=sigma=12,colorbalance=rh=0.3:gh=0.05:bh=-0.2[hlg0];[hla0][hlg0]blend=all_mode=screen:all_opacity=0.240"

[[case]]
name = "min"
at = "min"
chain = "split[hla0][hlb0];[hlb0]gblur=sigma=2,colorbalance=rh=0.3:gh=0.05:bh=-0.2[hlg0];[hla0][hlg0]blend=all_mode=screen:all_opacity=0.000"

[[case]]
name = "max"
at = "max"
chain = "split[hla0][hlb0];[hlb0]gblur=sigma=30,colorbalance=rh=0.3:gh=0.05:bh=-0.2[hlg0];[hla0][hlg0]blend=all_mode=screen:all_opacity=0.400"
