[[case]]
name = "default"
chain = "crop=iw-30:ih-30:15+15*sin(t*10):15+15*cos(t*13)"

[[case]]
name = "min"
at = "min"
chain = "crop=iw-2:ih-2:1+1*sin(t*2):1+1*cos(t*3)"

[[case]]
name = "max"
at = "max"
chain = "crop=iw-100:ih-100:50+50*sin(t*30):50+50*cos(t*39)"
