[[case]]
name = "default"
chain = "geq=r='r(X+4.00*sin(Y/10+T*3.00),Y+4.00*sin(X/10+T*3.00))':g='g(X+4.00*sin(Y/10+T*3.00),Y+4.00*sin(X/10+T*3.00))':b='b(X+4.00*sin(Y/10+T*3.00),Y+4.00*sin(X/10+T*3.00))'"

[[case]]
name = "min"
at = "min"
chain = "geq=r='r(X+0.00*sin(Y/10+T*0.50),Y+0.00*sin(X/10+T*0.50))':g='g(X+0.00*sin(Y/10+T*0.50),Y+0.00*sin(X/10+T*0.50))':b='b(X+0.00*sin(Y/10+T*0.50),Y+0.00*sin(X/10+T*0.50))'"

[[case]]
name = "max"
at = "max"
chain = "geq=r='r(X+8.00*sin(Y/10+T*6.00),Y+8.00*sin(X/10+T*6.00))':g='g(X+8.00*sin(Y/10+T*6.00),Y+8.00*sin(X/10+T*6.00))':b='b(X+8.00*sin(Y/10+T*6.00),Y+8.00*sin(X/10+T*6.00))'"
