[[case]]
name = "default"
chain = "chromashift=crh=4:cbh=-4,noise=alls=12:allf=t"

[[case]]
name = "min"
at = "min"
chain = "chromashift=crh=0:cbh=-0,noise=alls=0:allf=t"

[[case]]
name = "max"
at = "max"
chain = "chromashift=crh=6:cbh=-6,noise=alls=20:allf=t"
