[[case]]
name = "default"
chain = "noise=alls=8:allf=t+u,eq=contrast=0.975"

[[case]]
name = "min"
at = "min"
chain = "noise=alls=0:allf=t+u,eq=contrast=1.000"

[[case]]
name = "max"
at = "max"
chain = "noise=alls=15:allf=t+u,eq=contrast=0.950"
