[[case]]
name = "default"
chain = "eq=brightness=0.056:contrast=1.070"

[[case]]
name = "min"
at = "min"
chain = "eq=brightness=0.000:contrast=1.000"

[[case]]
name = "max"
at = "max"
chain = "eq=brightness=0.080:contrast=1.100"
