[[case]]
name = "default"
chain = "edgedetect=mode=colormix:low=0.136:high=0.390,eq=saturation=1.560"

[[case]]
name = "min"
at = "min"
chain = "edgedetect=mode=colormix:low=0.210:high=0.600,eq=saturation=1.000"

[[case]]
name = "max"
at = "max"
chain = "edgedetect=mode=colormix:low=0.105:high=0.300,eq=saturation=1.800"
