[[case]]
name = "default"
chain = "geq=r='r(X+4.00*sin(Y/15+T*2.00),Y+4.00*cos(X/15+T*2.00))':g='g(X+4.00*sin(Y/15+T*2.00),Y+4.00*cos(X/15+T*2.00))':b='b(X+4.00*sin(Y/15+T*2.00),Y+4.00*cos(X/15+T*2.00))'"

[[case]]
name = "min"
at = "min"
chain = "geq=r='r(X+0.00*sin(Y/15+T*0.50),Y+0.00*cos(X/15+T*0.50))':g='g(X+0.00*sin(Y/15+T*0.50),Y+0.00*cos(X/15+T*0.50))':b='b(X+0.00*sin(Y/15+T*0.50),Y+0.00*cos(X/15+T*0.50))'"

[[case]]
name = "max"
at = "max"
chain = "geq=r='r(X+10.00*sin(Y/15+T*10.00),Y+10.00*cos(X/15+T*10.00))':g='g(X+10.00*sin(Y/15+T*10.00),Y+10.00*cos(X/15+T*10.00))':b='b(X+10.00*sin(Y/15+T*10.00),Y+10.00*cos(X/15+T*10.00))'"
