[[case]]
name = "default"
chain = "hue=h=200,colorbalance=rh=0.04:bh=0.06"

[[case]]
name = "min"
at = "min"
chain = "hue=h=0,colorbalance=rh=0.04:bh=0.06"

[[case]]
name = "max"
at = "max"
chain = "hue=h=360,colorbalance=rh=0.04:bh=0.06"
