[[case]]
name = "default"
chain = "lenscorrection=k1=-0.075:k2=-0.075:i=bilinear"

[[case]]
name = "min"
at = "min"
chain = "lenscorrection=k1=0.000:k2=0.000:i=bilinear"

[[case]]
name = "max"
at = "max"
chain = "lenscorrection=k1=-0.250:k2=-0.250:i=bilinear"
