[[case]]
name = "default"
chain = "geq=r='r(W/2+(X-W/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':g='g(W/2+(X-W/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':b='b(W/2+(X-W/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.200*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))'"

[[case]]
name = "min"
at = "min"
chain = "geq=r='r(W/2+(X-W/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':g='g(W/2+(X-W/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':b='b(W/2+(X-W/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+-0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))'"

[[case]]
name = "max"
at = "max"
chain = "geq=r='r(W/2+(X-W/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':g='g(W/2+(X-W/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))':b='b(W/2+(X-W/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))),H/2+(Y-H/2)*(1+0.400*(1-min(hypot(X-W/2,Y-H/2)/(W/2),1))))'"
